# shellcheck shell=bash
# 10-texlive.sh — install TeX Live into the user's home directory.
#
# Design decisions, and why:
#   * user-local (no sudo). A password prompt is the single most common way an
#     unattended install dies, and nothing outside $HOME is ever touched.
#   * scheme-custom. In an install-tl profile, naming any *real* scheme makes
#     install-tl DELETE the collections you listed (install-tl source, the
#     'selected_scheme ne scheme-custom' branch). Only scheme-custom keeps an
#     explicit list, which is how we get "everything except most languages".
#   * the collection list is read from the live package database when possible,
#     so a future TeX Live that adds a collection still gets it. A hardcoded
#     list is the fallback.

# languages to keep (collection-lang*). langcjk is required by langjapanese.
TL_KEEP_LANGS="langenglish langspanish langfrench langitalian langportuguese langjapanese langcjk"

# Fallback list, used only if the package database cannot be downloaded.
TL_FALLBACK_NONLANG="basic bibtexextra binextra context fontsextra fontsrecommended
fontutils formatsextra games humanities latex latexextra latexrecommended luatex
mathscience metapost music pictures plaingeneric pstricks publishers xetex"

# Windows-only collections: pointless on macOS/Linux.
TL_EXCLUDE="wintools texworks"

tl_find_existing() {
  # Echo the bin directory of a usable TeX Live, or nothing.
  local p d y
  # 1. already on PATH?
  if have pdflatex && have tlmgr; then
    dirname "$(command -v pdflatex)"
    return 0
  fi
  # 2. under our prefix (any year, any platform)
  for d in "$TL_PREFIX"/*/bin/*; do
    [ -x "$d/pdflatex" ] && { echo "$d"; return 0; }
  done 2>/dev/null
  # 3. common system locations we must NOT touch, but should report
  for d in /usr/local/texlive/*/bin/* /opt/texlive/*/bin/* /Library/TeX/texbin; do
    [ -x "$d/pdflatex" ] && { echo "$d"; return 0; }
  done 2>/dev/null
  return 1
}

tl_collection_list() {
  # Print the collection names to install, one per line, WITHOUT the
  # "collection-" prefix. Tries the live database, falls back to the builtin list.
  local tmp="$1" db="$1/texlive.tlpdb" got=0 c
  if fetch "$TL_REPO/tlpkg/texlive.tlpdb.xz" "$db.xz"; then
    if have xz && xz -dc "$db.xz" > "$db" 2>/dev/null && [ -s "$db" ]; then got=1
    elif [ -n "$PYBIN" ] && "$PYBIN" -c "
import lzma,sys
open(sys.argv[2],'wb').write(lzma.open(sys.argv[1]).read())" "$db.xz" "$db" 2>/dev/null && [ -s "$db" ]; then got=1
    fi
  fi
  if [ "$got" = "0" ] && fetch "$TL_REPO/tlpkg/texlive.tlpdb" "$db"; then
    [ -s "$db" ] && got=1
  fi

  if [ "$got" = "1" ]; then
    # every collection in the database
    grep '^name collection-' "$db" | sed 's/^name collection-//' | sort -u
    return 0
  fi
  return 1
}

tl_build_profile() {
  # tl_build_profile OUTFILE COLLECTION_NAMES...
  local out="$1"; shift
  local c keep
  {
    echo "# TeX Live profile generated by latex-tools on $(date)"
    echo "# host: $(uname -a)"
    echo "selected_scheme scheme-custom"
    for c in "$@"; do echo "collection-$c 1"; done
    echo "TEXDIR $TL_DIR"
    echo "TEXMFLOCAL $TL_PREFIX/texmf-local"
    echo "TEXMFSYSVAR $TL_DIR/texmf-var"
    echo "TEXMFSYSCONFIG $TL_DIR/texmf-config"
    echo "TEXMFVAR $HOME/.texlive$TL_YEAR/texmf-var"
    echo "TEXMFCONFIG $HOME/.texlive$TL_YEAR/texmf-config"
    echo "TEXMFHOME $HOME/texmf"
    echo "instopt_adjustpath 0"      # never write into /usr/local/bin
    echo "instopt_adjustrepo 1"
    echo "instopt_letter 0"
    echo "instopt_portable 0"
    echo "instopt_write18_restricted 1"
    echo "tlpdbopt_autobackup 1"
    echo "tlpdbopt_backupdir tlpkg/backups"
    echo "tlpdbopt_create_formats 1"
    echo "tlpdbopt_desktop_integration 0"
    echo "tlpdbopt_file_assocs 0"
    echo "tlpdbopt_generate_updmap 0"
    echo "tlpdbopt_install_docfiles ${TL_DOCS}"
    echo "tlpdbopt_install_srcfiles 0"
    echo "tlpdbopt_post_code 1"
  } > "$out"
}

tl_verify() {
  # Compile a tiny document to prove the installation actually works.
  local bin="$1" t rc
  t=$(mktemp -d 2>/dev/null || mktemp -d -t ltv) || return 1
  # Note the author-year \bibitem form: natbib defaults to author-year and
  # rejects a bare numeric \bibitem with a fatal error.
  cat > "$t/probe.tex" <<'PROBE'
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{amsmath,graphicx,hyperref,natbib,booktabs}
\begin{document}
Hello $E=mc^2$ \citep{x}
\begin{thebibliography}{1}
\bibitem[Author(2020)]{x} Author, A. 2020, Journal, 1, 1
\end{thebibliography}
\end{document}
PROBE
  # NB: the redirect must NOT be called probe.out - hyperref uses \jobname.out
  # for its bookmarks and reads it back, so a shell redirect of that name makes
  # the run fail with a baffling "Missing { inserted" on the pdfTeX banner.
  ( cd "$t" && "$bin/pdflatex" -interaction=nonstopmode -halt-on-error probe.tex >run.txt 2>&1 )
  rc=$?
  if [ $rc -eq 0 ] && [ -s "$t/probe.pdf" ]; then rm -rf "$t"; return 0; fi
  cp "$t/run.txt" "${LOGFILE:-/dev/null}.probe" 2>/dev/null

  # The rich probe failed. Find out whether TeX itself is broken, or whether
  # it merely lacks one of the packages/fonts the probe asked for - a very
  # different problem, and worth saying precisely.
  # pdfTeX wraps its errors across lines and embeds the full binary path, so
  # collapse the first few lines and shorten the path to stay readable.
  TL_VERIFY_DETAIL=$(grep -m1 -A3 -E '^(!|!pdfTeX error)' "$t/run.txt" 2>/dev/null \
      | tr '\n' ' ' \
      | sed -e 's#/[^ ]*/pdflatex#pdflatex#g' -e 's/  */ /g' -e 's/^ *//' \
      | cut -c1-160)
  cat > "$t/bare.tex" <<'BARE'
\documentclass{article}
\begin{document}Hello.\end{document}
BARE
  ( cd "$t" && "$bin/pdflatex" -interaction=nonstopmode -halt-on-error bare.tex >bare.txt 2>&1 )
  if [ -s "$t/bare.pdf" ]; then rm -rf "$t"; return 2; fi   # TeX works, packages missing
  rm -rf "$t"
  return 1                                                  # TeX itself is broken
}

install_texlive() {
  step "TeX Live"

  local existing
  existing=$(tl_find_existing 2>/dev/null || true)
  if [ -n "$existing" ]; then
    case "$existing" in
      /usr/local/texlive/*|/Library/TeX/*|/opt/texlive/*)
        ok "an existing system-wide TeX Live is already installed:"
        info "$existing"
        info "leaving it completely alone - nothing to do"
        TL_BIN="$existing"
        return 0 ;;
      *)
        ok "TeX Live already present: $existing"
        tl_verify "$existing"; local v=$?
        if [ $v -eq 0 ]; then
          info "it compiles a test document correctly - keeping it"
          TL_BIN="$existing"
          return 0
        elif [ $v -eq 2 ]; then
          # TeX itself runs; only an optional package/font is absent. That is
          # never worth a multi-GB reinstall, so keep what is already there.
          warn "TeX works, but a package or font the test document needs is missing:"
          info "${TL_VERIFY_DETAIL:-unknown}"
          info "add it with:  $existing/tlmgr install <package>"
          info "keeping the existing installation (a missing package is not worth a reinstall)"
          TL_BIN="$existing"
          return 0
        else
          warn "TeX Live is present but does not work at all"
          if ! confirm "reinstall TeX Live?"; then TL_BIN="$existing"; return 0; fi
        fi ;;
    esac
  fi

  # ---- space check -------------------------------------------------------
  local need free
  if [ "$TL_MINIMAL" = "1" ]; then need=400; else need=10000; fi
  free=$(free_space_mb "$TL_PREFIX")
  if [ -n "$free" ] && [ "$free" -lt "$need" ] 2>/dev/null; then
    die "not enough free disk space: ${free} MB available, about ${need} MB needed"
  fi
  info "free disk space: ${free:-unknown} MB (need about ${need} MB)"

  # ---- installer ---------------------------------------------------------
  local tmp
  tmp=$(mktemp -d 2>/dev/null || mktemp -d -t tlinst) || die "cannot create a temp directory"
  TL_TMP="$tmp"

  info "downloading the TeX Live installer..."
  local mirror
  mirror=$(fetch_from_mirrors "install-tl-unx.tar.gz" "$tmp/install-tl-unx.tar.gz") || \
    die "could not download the installer from any CTAN mirror (check the network)"
  TL_REPO="$mirror"
  ok "mirror: $mirror"
  info "installer: $(human_size "$(wc -c < "$tmp/install-tl-unx.tar.gz" | tr -d ' ')")"

  tar xzf "$tmp/install-tl-unx.tar.gz" -C "$tmp" || die "the downloaded installer is corrupt"
  local idir
  idir=$(find "$tmp" -maxdepth 1 -type d -name 'install-tl-*' | head -1)
  [ -n "$idir" ] || die "unexpected installer layout"

  have perl || die "perl is required by the TeX Live installer but was not found"

  # platform + year, straight from the installer itself
  local plat year
  plat=$("$idir/install-tl" --print-platform 2>/dev/null | tr -d '[:space:]')
  [ -n "$plat" ] || plat=$(guess_tl_platform)
  [ -n "$plat" ] || die "unsupported platform: $(uname -s)/$(uname -m)"
  year=$("$idir/install-tl" --version 2>/dev/null | sed -n 's/.*version \([0-9][0-9]*\).*/\1/p' | head -1)
  [ -n "$year" ] || year=$(date +%Y)
  TL_PLATFORM="$plat"; TL_YEAR="$year"; TL_DIR="$TL_PREFIX/$year"
  ok "TeX Live $year for $plat"

  # ---- which collections -------------------------------------------------
  local all sel c keep line
  all=$(tl_collection_list "$tmp" 2>/dev/null || true)
  sel=""
  if [ -n "$all" ]; then
    ok "package database read ($(echo "$all" | wc -l | tr -d ' ') collections available)"
    for c in $all; do
      case "$c" in
        lang*)
          for keep in $TL_KEEP_LANGS; do
            [ "$c" = "$keep" ] && sel="$sel $c"
          done ;;
        *)
          local excluded=0
          for keep in $TL_EXCLUDE; do [ "$c" = "$keep" ] && excluded=1; done
          [ "$excluded" = "0" ] && sel="$sel $c" ;;
      esac
    done
  else
    warn "could not read the package database - using the built-in collection list"
    for c in $TL_FALLBACK_NONLANG; do sel="$sel $c"; done
    for c in $TL_KEEP_LANGS; do sel="$sel $c"; done
  fi

  if [ "$TL_MINIMAL" = "1" ]; then
    warn "--minimal: installing only collection-basic + latex (for testing)"
    sel="basic latex latexrecommended langenglish"
  fi

  info "collections to install: $(echo $sel | wc -w | tr -d ' ')"
  info "languages: $(echo $TL_KEEP_LANGS | sed 's/lang//g')"

  tl_build_profile "$tmp/tl.profile" $sel
  cp "$tmp/tl.profile" "${LOGFILE:-/dev/null}.profile" 2>/dev/null || true

  if [ "$DRYRUN" = "1" ]; then
    info "[dry-run] would run install-tl with the profile above into $TL_DIR"
    TL_BIN="$TL_DIR/bin/$plat"
    return 0
  fi

  # ---- run ---------------------------------------------------------------
  info "installing into $TL_DIR"
  info "this takes roughly 20-40 minutes and downloads several GB - please leave it running"
  mkdir -p "$TL_PREFIX" || die "cannot create $TL_PREFIX"

  local attempt rc=1 m
  attempt=0
  for m in $TL_REPO $CTAN_MIRRORS; do
    attempt=$((attempt+1))
    [ $attempt -gt 3 ] && break
    info "attempt $attempt using $m"
    "$idir/install-tl" -profile "$tmp/tl.profile" -repository "$m" \
        >> "${LOGFILE:-/dev/null}" 2>&1
    rc=$?
    [ $rc -eq 0 ] && break
    warn "that attempt failed (exit $rc); trying another mirror"
  done
  [ $rc -eq 0 ] || die "TeX Live installation failed. See the log: ${LOGFILE:-<none>}"

  TL_BIN="$TL_DIR/bin/$plat"
  [ -x "$TL_BIN/pdflatex" ] || die "install finished but $TL_BIN/pdflatex is missing"
  record "texlive|$TL_DIR"
  ok "installed: $TL_DIR"

  tl_verify "$TL_BIN"; local v=$?
  if [ $v -eq 0 ]; then
    ok "test document compiles correctly (amsmath, graphicx, hyperref, natbib, booktabs)"
  elif [ $v -eq 2 ]; then
    if [ "$TL_MINIMAL" = "1" ]; then
      ok "TeX works (the richer test needs packages --minimal does not install - expected)"
    else
      warn "TeX works, but the test document needs something that is missing:"
      info "${TL_VERIFY_DETAIL:-unknown}"
      info "add it with:  $TL_BIN/tlmgr install <package>"
    fi
  else
    warn "TeX Live does not run - the installation looks incomplete"
    info "see the log: ${LOGFILE:-<none>}"
  fi
  rm -rf "$tmp"
  return 0
}

configure_texlive_path() {
  step "PATH setup"

  # Two independent things go on PATH: TeX Live (only if we installed it into
  # the home directory) and ~/.local/bin (always, that is where paperdiff goes).
  local want_tex=1
  if [ -z "${TL_BIN:-}" ]; then
    want_tex=0
  else
    case "$TL_BIN" in
      /usr/local/texlive/*|/Library/TeX/*|/opt/texlive/*)
        info "system TeX Live is already on PATH - only adding ~/.local/bin"
        want_tex=0 ;;
    esac
  fi

  # If any startup file already points at this TeX Live, do nothing at all.
  # The guard is the $HOME-relative tail of the path, because an existing block
  # may well have been written as "$HOME/texlive/..." rather than expanded.
  local guard f
  if [ "$want_tex" = "1" ]; then
    guard="${TL_BIN#$HOME/}"
    [ "$guard" = "$TL_BIN" ] && guard="$TL_BIN"
  else
    guard=".local/bin"
  fi
  for f in "$HOME/.bash_profile" "$HOME/.zshrc" "$HOME/.profile" "$HOME/.bashrc" "$HOME/.zprofile"; do
    if [ -f "$f" ] && grep -qF "$guard" "$f" 2>/dev/null; then
      ok "already on PATH via $(basename "$f") - shell files left untouched"
      return 0
    fi
  done

  # Appended, never prepended: anything you already have (MacPorts, Homebrew,
  # conda) keeps priority, so this cannot shadow an existing tool.
  local blockfile
  blockfile=$(mktemp 2>/dev/null || echo "${TMPDIR:-/tmp}/latex-tools-block.$$")
  {
    echo "# TeX Live + paperdiff, added by latex-tools on $(date '+%Y-%m-%d')."
    echo "# Appended (not prepended) so it cannot shadow Homebrew/MacPorts/conda tools."
  } > "$blockfile"
  if [ "$want_tex" = "1" ]; then
    cat >> "$blockfile" <<EOF
if [ -d "$TL_BIN" ]; then
    export PATH="\$PATH:$TL_BIN"
    export MANPATH="\${MANPATH:-}:$TL_DIR/texmf-dist/doc/man"
    export INFOPATH="\${INFOPATH:-}:$TL_DIR/texmf-dist/doc/info"
fi
EOF
  fi
  cat >> "$blockfile" <<EOF
if [ -d "\$HOME/.local/bin" ]; then
    case ":\$PATH:" in
        *":\$HOME/.local/bin:"*) ;;
        *) export PATH="\$HOME/.local/bin:\$PATH" ;;
    esac
fi
EOF

  local f touched=0
  for f in "$HOME/.bash_profile" "$HOME/.zshrc" "$HOME/.profile"; do
    # Only create files that already exist, except .bash_profile/.zshrc which
    # are the two that actually matter for login shells.
    case "$f" in
      "$HOME/.profile") [ -f "$f" ] || continue ;;
    esac
    append_block "$f" "$blockfile" "$guard" && touched=1
  done
  rm -f "$blockfile" 2>/dev/null
  [ "$touched" = "1" ] || info "your shell files already point at this TeX Live"
  return 0
}
